security:
    password_hashers:
        # Configuration du hachage des mots de passe pour l'entité Email
        App\Entity\Email: auto

    providers:
        users_in_memory: 
            entity:
                class: App\Entity\Email  # Utilisation de l'entité Email pour l'authentification
                property: email  # Authentifie par l'email

    firewalls:
        # Firewall pour l'environnement de développement (profiler, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal
        main:
            lazy: true
            provider: users_in_memory
            form_login:
                login_path: app_login  # Route de la page de connexion
                check_path: app_login  # Vérification des identifiants
                default_target_path: app_home  # Chemin de redirection après une connexion réussie
            logout:
                path: app_logout  # Route de déconnexion
                target: app_home  # Redirection après déconnexion

    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Accessible sans authentification
        # - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Accessible sans authentification
        # - { path: ^/, roles: ROLE_USER }  # Toutes les autres routes nécessitent que l'utilisateur soit connecté

parameters:
    product_images_directory: '%kernel.project_dir%/public/uploads/images'
